apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demokotlin
  name: demokotlin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demokotlin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demokotlin
    spec:
      containers:
        - image: demokotlin
          name: demokotlin
          imagePullPolicy: Never
          resources: {}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: demokotlin-config
status: {}